"""Type stubs for the compiled Rust extension (``lytk._core``)."""

from __future__ import annotations

from typing import Any

class Score:
    """Opaque handle to a parsed music score."""

    @property
    def title(self) -> str | None: ...
    @property
    def composer(self) -> str | None: ...
    @property
    def subtitle(self) -> str | None: ...
    @property
    def arranger(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...
    @property
    def num_parts(self) -> int: ...
    @property
    def parts(self) -> list[str]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> Score: ...
    def to_dict(self) -> dict[str, Any]: ...
    @staticmethod
    def from_dict(dict: dict[str, Any]) -> Score: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MusicDocument:
    """Opaque handle to a parsed music document (Layer 1 Music tree)."""

    @property
    def title(self) -> str | None: ...
    @property
    def composer(self) -> str | None: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> MusicDocument: ...
    def to_score(self) -> Score: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

# -- Adapters ----------------------------------------------------------------

def from_musicxml(path: str) -> Score: ...
def from_musicxml_string(xml: str) -> Score: ...
def from_lilypond(path: str, *, language: str | None = None) -> Score: ...
def from_lilypond_string(text: str, *, language: str | None = None) -> Score: ...
def from_lilypond_music(
    path: str, *, language: str | None = None
) -> MusicDocument: ...
def from_lilypond_music_string(
    text: str, *, language: str | None = None
) -> MusicDocument: ...
def to_lilypond(
    score: Score,
    path: str | None = None,
    *,
    language: str | None = None,
) -> str: ...
def to_lilypond_music(
    doc: MusicDocument, path: str | None = None
) -> str: ...
def to_musicxml(score: Score, path: str | None = None) -> str: ...

# MIDI (only available when built with the "midi" feature)
def from_midi(path: str) -> Score: ...
def to_midi(score: Score, path: str) -> None: ...

# -- Transforms --------------------------------------------------------------

def transpose(score: Score, semitones: int) -> Score: ...
def change_language(score: Score, language: str) -> Score: ...
def invert(
    score: Score,
    *,
    step: str = "C",
    alter: int = 0,
    octave: int = 4,
) -> Score: ...
def retrograde(score: Score) -> Score: ...
