"""Type stubs for the compiled Rust extension (``lytk._core``)."""

from __future__ import annotations

from typing import Any, TypeVar

class Score:
    """Opaque handle to a parsed music score."""

    @property
    def title(self) -> str | None: ...
    @property
    def composer(self) -> str | None: ...
    @property
    def subtitle(self) -> str | None: ...
    @property
    def arranger(self) -> str | None: ...
    @property
    def lyricist(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...
    @property
    def num_parts(self) -> int: ...
    @property
    def parts(self) -> list[str]: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> Score: ...
    def to_dict(self) -> dict[str, Any]: ...
    @staticmethod
    def from_dict(dict: dict[str, Any]) -> Score: ...
    def to_music_document(self) -> MusicDocument: ...
    def notes(self, resolution: int = 480) -> list[tuple[int, int, int, int]]:
        """Notes as ``(onset, duration, pitch, velocity)`` tuples in time steps."""
        ...
    def iter_parts(self) -> list[Part]:
        """Structured navigation: parts as typed :class:`Part` objects."""
        ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class MusicDocument:
    """Opaque handle to a parsed music document (Layer 1 Music tree)."""

    @property
    def title(self) -> str | None: ...
    @property
    def composer(self) -> str | None: ...
    @property
    def subtitle(self) -> str | None: ...
    @property
    def arranger(self) -> str | None: ...
    @property
    def language(self) -> str | None: ...
    def notes(self, resolution: int = 480) -> list[tuple[int, int, int, int]]:
        """Notes as ``(onset, duration, pitch, velocity)`` tuples in time steps."""
        ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(json: str) -> MusicDocument: ...
    def to_score(self) -> Score: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

# -- Structured note navigation (read-only Layer-2 tree) ---------------------

class Pitch:
    """A note's pitch (read-only)."""

    @property
    def step(self) -> str:
        """Diatonic step name, e.g. ``"C"``."""
        ...
    @property
    def alter(self) -> int:
        """Chromatic alteration in semitones (1 = sharp, -1 = flat)."""
        ...
    @property
    def octave(self) -> int: ...
    @property
    def midi(self) -> int:
        """MIDI note number (middle C = 60)."""
        ...
    @property
    def name(self) -> str:
        """Scientific pitch name, e.g. ``"C#4"``."""
        ...
    def __repr__(self) -> str: ...

class Note:
    """A single pitched note (read-only)."""

    @property
    def pitch(self) -> Pitch: ...
    @property
    def midi(self) -> int: ...
    @property
    def duration(self) -> float:
        """Duration in quarter-note lengths."""
        ...
    @property
    def duration_fraction(self) -> tuple[int, int]:
        """Exact duration as ``(numerator, denominator)`` of a whole note."""
        ...
    @property
    def voice(self) -> int: ...
    @property
    def staff(self) -> int: ...
    @property
    def is_grace(self) -> bool: ...
    @property
    def ties(self) -> list[str]:
        """Tie events: ``"start"`` / ``"stop"`` / ``"continue"``."""
        ...
    @property
    def articulations(self) -> list[str]: ...
    @property
    def lyrics(self) -> list[str]: ...
    def __repr__(self) -> str: ...

class Rest:
    """A rest or spacer (read-only)."""

    @property
    def duration(self) -> float: ...
    @property
    def duration_fraction(self) -> tuple[int, int]: ...
    @property
    def voice(self) -> int: ...
    @property
    def staff(self) -> int: ...
    @property
    def is_measure_rest(self) -> bool: ...
    @property
    def is_spacer(self) -> bool: ...
    def __repr__(self) -> str: ...

class Chord:
    """A chord — notes sounding together (read-only)."""

    @property
    def duration(self) -> float: ...
    @property
    def duration_fraction(self) -> tuple[int, int]: ...
    @property
    def voice(self) -> int: ...
    @property
    def staff(self) -> int: ...
    @property
    def notes(self) -> list[Note]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Voice:
    """A voice within a measure (read-only)."""

    @property
    def number(self) -> int: ...
    @property
    def elements(self) -> list[Note | Rest | Chord]: ...
    @property
    def notes(self) -> list[Note]:
        """Every sounding note (chord members flattened)."""
        ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Measure:
    """A measure / bar (read-only)."""

    @property
    def number(self) -> int: ...
    @property
    def number_label(self) -> str | None: ...
    @property
    def implicit(self) -> bool: ...
    @property
    def senza_misura(self) -> bool: ...
    @property
    def time_signature(self) -> tuple[str, int, str | None] | None:
        """``(beats, beat_type, symbol)`` if set at this measure, else None."""
        ...
    @property
    def key_signature(self) -> tuple[int, str] | None:
        """``(fifths, mode)`` if set at this measure, else None."""
        ...
    @property
    def voices(self) -> list[Voice]: ...
    @property
    def notes(self) -> list[Note]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Part:
    """An instrument part — a sequence of measures (read-only)."""

    @property
    def name(self) -> str: ...
    @property
    def abbreviation(self) -> str: ...
    @property
    def part_id(self) -> str: ...
    @property
    def midi_program(self) -> int: ...
    @property
    def midi_instrument(self) -> str: ...
    @property
    def midi_channel(self) -> int: ...
    @property
    def staves(self) -> int: ...
    @property
    def measures(self) -> list[Measure]: ...
    @property
    def notes(self) -> list[Note]:
        """Every sounding note in the part."""
        ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

# -- Adapters ----------------------------------------------------------------

def from_musicxml(path: str) -> Score: ...
def from_musicxml_string(xml: str) -> Score: ...
def from_musicxml_bytes(data: bytes) -> Score:
    """Parse MusicXML or compressed MXL from in-memory bytes."""
    ...
def from_lilypond(path: str, *, language: str | None = None) -> Score: ...
def from_lilypond_string(text: str, *, language: str | None = None) -> Score: ...
def from_lilypond_movements(path: str, *, language: str | None = None) -> list[Score]:
    """Every movement of a LilyPond file: one score per ``\\score`` block."""
    ...
def from_lilypond_music(
    path: str, *, language: str | None = None
) -> MusicDocument: ...
def from_lilypond_music_string(
    text: str, *, language: str | None = None
) -> MusicDocument: ...
def to_lilypond(
    score: Score,
    path: str | None = None,
    *,
    language: str | None = None,
    relative: bool | None = None,
) -> str:
    """*relative*: ``True`` for ``\\relative`` entry, ``False`` for absolute,
    ``None`` for the score's own."""
    ...
def to_lilypond_music(
    doc: MusicDocument, path: str | None = None
) -> str: ...
def to_musicxml(score: Score, path: str | None = None) -> str: ...
def to_mxl_bytes(score: Score) -> bytes:
    """Serialize a score to compressed MusicXML (a ZIP archive)."""
    ...
def flatten(
    input: str,
    output: str | None = None,
    *,
    include_paths: list[str] | None = None,
    add_markers: bool = True,
) -> str: ...
def from_abc(path: str) -> Score: ...
def from_abc_string(text: str) -> Score: ...
def to_abc(score: Score, path: str | None = None) -> str: ...
def from_humdrum(path: str) -> Score: ...
def from_humdrum_string(text: str) -> Score: ...
def to_humdrum(score: Score, path: str | None = None) -> str: ...

# MIDI (always built in)
def from_midi(path: str) -> Score: ...
def from_midi_bytes(data: bytes) -> Score:
    """Parse a Standard MIDI File from in-memory bytes."""
    ...
def to_midi(score: Score, path: str) -> None: ...
def to_midi_bytes(score: Score) -> bytes:
    """Serialize a score to Standard MIDI File bytes."""
    ...

# -- Transforms --------------------------------------------------------------

_M = TypeVar("_M", Score, MusicDocument)

def transpose(music: _M, semitones: int) -> _M: ...
def transpose_interval(music: _M, interval: str) -> _M: ...
def transpose_to_key(music: _M, key: str) -> _M: ...
def change_language(music: _M, language: str) -> _M: ...
def invert(
    music: _M,
    *,
    step: str = "C",
    alter: int = 0,
    octave: int = 4,
) -> _M: ...
def retrograde(music: _M) -> _M: ...

# -- ML representations (Epic D) ---------------------------------------------

import numpy as np
import numpy.typing as npt

def to_note_array(
    doc: MusicDocument, resolution: int = 480
) -> npt.NDArray[np.int32]:
    """Encode a document as a ``(N, 4)`` array: (onset, duration, pitch, velocity)."""
    ...

def from_note_array(
    array: npt.NDArray[np.int32], resolution: int = 480
) -> MusicDocument:
    """Decode a ``(N, 4)`` note array back into a document."""
    ...

def to_event_sequence(
    doc: MusicDocument,
    resolution: int = 480,
    max_time_shift: int = 100,
    velocity_bins: int = 32,
    encode_velocity: bool = True,
) -> npt.NDArray[np.int64]:
    """Encode a document as a 1-D event-code sequence (Performance-RNN style)."""
    ...

def from_event_sequence(
    array: npt.NDArray[np.int64],
    resolution: int = 480,
    max_time_shift: int = 100,
    velocity_bins: int = 32,
    encode_velocity: bool = True,
) -> MusicDocument:
    """Decode an event-code sequence back into a document."""
    ...

def to_piano_roll(
    doc: MusicDocument, resolution: int = 480, encode_velocity: bool = True
) -> npt.NDArray[np.uint8]:
    """Encode a document as a ``(T, 128)`` piano-roll matrix."""
    ...

def from_piano_roll(
    array: npt.NDArray[np.uint8],
    resolution: int = 480,
    encode_velocity: bool = True,
) -> MusicDocument:
    """Decode a ``(T, 128)`` piano-roll matrix back into a document."""
    ...

def compute_metrics(
    doc: MusicDocument,
    resolution: int = 480,
    measure_resolution: int | None = None,
) -> dict[str, Any]:
    """Compute objective evaluation metrics (NaN where undefined).

    Keys: n_pitches_used, n_pitch_classes_used, pitch_range,
    pitch_class_histogram, pitch_entropy, pitch_class_entropy, polyphony,
    polyphony_rate, empty_beat_rate, scale_consistency, groove_consistency.
    """
    ...
